version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: cfwdb
      POSTGRES_USER: cfwuser
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: 
      context: ./backend/djangocfw
      dockerfile: Dockerfile
    volumes:
      - ./backend/djangocfw:/app
      - ./data:/app/data
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=cfwdb
      - DB_USER=cfwuser
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - PLANET_API_KEY=${PLANET_API_KEY}
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - VITE_API_URL=http://localhost:8000/api

volumes:
  postgres_data: