services:
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - TZ=America/New_York

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  backend:
    build: 
      context: ./backend/djangocfw
      dockerfile: Dockerfile
    volumes:
      - ./data/planet_quads:/app/data/planet_quads
      - ./data/predictions:/app/data/predictions
      - ./data/models:/app/data/models
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    command: gunicorn djangocfw.wsgi:application --bind 0.0.0.0:8000 --workers 3
    restart: always
    environment:
      - TZ=America/New_York

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VUE_APP_PLANET_API_KEY: ${VUE_APP_PLANET_API_KEY}
        VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
        DJANGO_DEBUG: "False"  # Default to production
      target: "production"       # Use 'development' or 'production'
    ports:
      - "9000:9000"
    volumes:
      - ./data/predictions:/app/data/predictions:ro
      - ./data/planet_quads:/app/data/planet_quads:ro
      - ./data/models:/app/data/models:ro
    env_file:
      - ./.env.prod
    restart: always
    environment:
      - TZ=America/New_York
titiler:
    image: ghcr.io/developmentseed/titiler:latest
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - ./titiler/cogs:/data
      - ./titiler/mosaics:/mosaics
      - ./titiler/scripts:/scripts
    # environment:
    #   - TILER_CACHE_DISABLE=true
    #   - TILER_CACHE_TYPE=null
    #   - TILER_CACHE_HOST=null
    #   - TILER_CACHE_PORT=null
    #   - TILER_CACHE_USERNAME=null
    #   - TILER_CACHE_PASSWORD=null
    #   - TILER_API_CORS_ORIGINS=["*"]
    #   - TILER_API_CORS_METHODS=["GET"]
    #   - TILER_API_CORS_HEADERS=["*"]
    #   - TZ=America/New_York
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    command: >
      bash -c "chmod +x /scripts/build_all_mosaics.sh &&
              /scripts/build_all_mosaics.sh &&
              uvicorn titiler.application.main:app --host 0.0.0.0 --port 80"

volumes:
  postgres_data:  
