services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=cfwdb
      - POSTGRES_USER=cfwuser
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cfwuser -d cfwdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: 
      context: ./backend/djangocfw
      dockerfile: Dockerfile
    volumes:
      - ./backend/djangocfw:/app
      - ./data:/app/data
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=cfwdb
      - POSTGRES_USER=cfwuser
      - POSTGRES_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - PLANET_API_KEY=${PLANET_API_KEY}
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure:3
    entrypoint: ["/app/entrypoint.sh"]

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - VITE_API_URL=http://localhost:8000/api

volumes:
  postgres_data: