services:
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cfwuser -d cfwdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: 
      context: ./backend/djangocfw
      dockerfile: Dockerfile
    volumes:
      - ./backend/djangocfw:/app
      - ./data:/app/data
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
      - "5678:5678"
      - "3000:3000"
    env_file:
      - ./.env
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure:3

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    env_file:
      - ./.env

volumes:
  postgres_data: