# Generated by Django 5.1.3 on 2024-11-18 17:03

import core.storage
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingTask',
            fields=[
                ('task_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=25, null=True, storage=core.storage.PredictionStorage(), upload_to='')),
                ('basemap_date', models.CharField(max_length=7, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary_statistics', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('aoi', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.JSONField(default=list)),
                ('aoi_area_ha', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeforestationHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField()),
                ('area_ha', models.FloatField()),
                ('perimeter_m', models.FloatField()),
                ('compactness', models.FloatField()),
                ('edge_density', models.FloatField()),
                ('centroid_lon', models.FloatField()),
                ('centroid_lat', models.FloatField()),
                ('verification_status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='ml', max_length=20)),
                ('confidence', models.IntegerField(null=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='core.prediction')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.project'),
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_set_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('training_periods', models.IntegerField(null=True)),
                ('num_training_samples', models.IntegerField(null=True)),
                ('model_file', models.CharField(blank=True, max_length=255)),
                ('model_parameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('encoders', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.trainedmodel'),
        ),
        migrations.CreateModel(
            name='TrainingPolygonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('basemap_date', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_count', models.IntegerField(null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('polygons', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_polygon_sets', to='core.project')),
            ],
        ),
    ]
