# Generated by Django 5.1.3 on 2024-11-14 10:59

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('aoi', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.JSONField(default=list)),
                ('aoi_area_ha', models.FloatField(null=True)),
            ],
        ),
    ]
