# Generated by Django 5.1.3 on 2024-11-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trainedmodel_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainedmodel',
            name='unique_project_model',
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
