# Generated by Django 5.1.3 on 2024-11-20 11:46

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trainedmodel_unique_project_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='all_class_names',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.ModelStorage(), upload_to='models'),
        ),
    ]
