# Generated by Django 5.1.3 on 2024-12-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='seen_welcome_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seen_welcome_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seen_welcome_training',
            field=models.BooleanField(default=False),
        ),
    ]
