# Generated by Django 5.1.5 on 2025-01-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_is_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_models', models.IntegerField(default=0)),
                ('total_area_ha', models.FloatField(default=0)),
                ('total_hotspots', models.IntegerField(default=0)),
                ('active_users_30d', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Statistics',
                'verbose_name_plural': 'System Statistics',
            },
        ),
    ]
