# Generated by Django 5.2.3 on 2025-06-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='deforestationhotspot',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deforestationhotspot',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='core.prediction'),
        ),
        migrations.AddIndex(
            model_name='deforestationhotspot',
            index=models.Index(fields=['source'], name='core_defore_source_b43e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='deforestationhotspot',
            index=models.Index(fields=['year'], name='core_defore_year_9a2880_idx'),
        ),
        migrations.AddIndex(
            model_name='deforestationhotspot',
            index=models.Index(fields=['source', 'year'], name='core_defore_source_57edcc_idx'),
        ),
    ]
