"""add area column to projects

Revision ID: 65310e86379c
Revises: d102518c5b51
Create Date: 2024-11-05 06:31:07.021268

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.functions import ST_Area
from geoalchemy2.types import Geometry
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '65310e86379c'
down_revision = 'd102518c5b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aoi_area_ha', sa.Float(), nullable=True))

        # Update existing records
    connection = op.get_bind()
    
   # Calculate area directly from EPSG:4326 geometry
    connection.execute(text("""
        UPDATE project 
        SET aoi_area_ha = ST_Area(aoi::geography) / 10000
        WHERE aoi IS NOT NULL;
    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('aoi_area_ha')

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
