name: Deploy to Production (DigitalOcean)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and save Docker images
        run: |
          # Build all services
          docker compose -f docker-compose.prod.yml build
          
          # Save the images
          docker save $(docker compose -f docker-compose.prod.yml config --services | xargs -I{} echo cfw-{}:latest) | gzip > images.tar.gz

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          source: "images.tar.gz"
          target: "/root/opt/chocoforestwatch/"
          strip_components: 0

      - name: Load and run containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/opt/chocoforestwatch
            docker load < images.tar.gz
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d
            rm images.tar.gz 